=== Pegasenok/commissions/src/Resources/Schema/bin_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "number": {
            "type": "object",
            "properties": {
                "length": { "type": "integer" },
                "luhn": { "type": "boolean" }
            },
            "additionalProperties": false
        },
        "scheme": { "type": "string" },
        "type": { "type": "string" },
        "brand": { "type": "string" },
        "prepaid": { "type": ["boolean", "null"] },
        "country": {
            "type": "object",
            "properties": {
                "numeric": { "type": "string", "pattern": "^[0-9]{3}$" },
                "alpha2": { "type": "string", "pattern": "^[A-Z]{2}$" },
                "name": { "type": "string" },
                "emoji": { "type": "string" },
                "currency": { "type": "string", "pattern": "^[A-Z]{3}$" },
                "latitude": { "type": "number" },
                "longitude": { "type": "number" }
            },
            "required": ["numeric", "alpha2", "name", "emoji", "currency", "latitude", "longitude"],
            "additionalProperties": false
        },
        "bank": {
            "type": "object",
            "properties": {
                "name": { "type": "string" },
                "url": { "type": "string", "format": "uri" },
                "phone": { "type": "string" },
                "city": { "type": "string" }
            },
            "required": ["name"],
            "additionalProperties": false
        }
    },
    "required": ["number", "scheme", "type", "brand", "country", "bank"],
    "additionalProperties": false
}

=== Pegasenok/commissions/var/binlist_cache/41417360.json
{
    "number": {},
    "scheme": "visa",
    "type": "credit",
    "brand": "Visa Classic",
    "country": {
        "numeric": "392",
        "alpha2": "US",
        "name": "USA",
        "emoji": "🇯🇵",
        "currency": "USD",
        "latitude": 36,
        "longitude": 138
    },
    "bank": {
        "name": "VERMONT NATIONAL BANK"
    }
}
